version: '3.8'
services:
  fhir-mapper:
    build:
      context: .
      dockerfile: Dockerfile
    image: fhir-mapper
    ports:
      - '8085:8085'
    networks:
      - docker_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27018:27017'
    volumes:
      - mongodb_vol:/data/db
      - ./import_snomed.sh:/docker-entrypoint-initdb.d/import_snomed.sh
      - ./snomed:/docker-entrypoint-initdb.d/snomed
    networks:
      - docker_network

volumes:
  mongodb_vol:

networks:
  docker_network:
    driver: bridge